const CONSTANTS = {
  CANVAS_WIDTH: 600,
  CANVAS_HEIGHT: 800,
  WALL_THICKNESS: 60,
  GROUND_HEIGHT: 60,
  FRUIT_BASE_RADIUS: 4,
  FRUIT_SIZE_INCREMENT: 20
};

CONSTANTS.START_Y_OFFSET = CONSTANTS.FRUIT_BASE_RADIUS + 1

export default CONSTANTS;
